2020-01-02 12:31:15,096 ERROR: Exception on /index [GET] [in /Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/app/routes.py", line 29, in index
    page, application.config['POSTS_PER_PAGE', False])
KeyError: ('POSTS_PER_PAGE', False)
2020-01-02 12:31:56,111 INFO: Microblog startup [in /Users/nathanphan/Desktop/Projects/flask/microblog/app/__init__.py:49]
2020-01-02 12:46:49,093 INFO: Microblog startup [in /Users/nathanphan/Desktop/Projects/flask/microblog/app/__init__.py:49]
2020-01-02 12:49:17,140 INFO: Microblog startup [in /Users/nathanphan/Desktop/Projects/flask/microblog/app/__init__.py:49]
2020-01-02 12:53:02,229 INFO: Microblog startup [in /Users/nathanphan/Desktop/Projects/flask/microblog/app/__init__.py:49]
2020-01-02 12:59:55,459 INFO: Microblog startup [in /Users/nathanphan/Desktop/Projects/flask/microblog/app/__init__.py:49]
2020-01-02 14:30:04,479 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:49]
2020-01-02 14:30:14,554 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:49]
2020-01-02 15:03:36,449 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:04:02,557 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:08:40,536 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:45:17,119 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:45:30,773 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:45:53,664 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:46:01,966 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:46:12,680 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:46:27,517 ERROR: Exception on /reset_password_request [POST] [in /Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/routes.py", line 163, in reset_password_request
    send_password_reset_email(user)
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/email.py", line 6, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/models.py", line 40, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
NameError: name 'app' is not defined
2020-01-02 15:47:10,781 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:47:23,694 ERROR: Exception on /reset_password_request [POST] [in /Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/routes.py", line 163, in reset_password_request
    send_password_reset_email(user)
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/email.py", line 8, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-01-02 15:47:49,791 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
2020-01-02 15:51:09,899 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:51]
