2020-01-02 12:29:26,436 ERROR: Exception on /explore [GET] [in /Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/app/routes.py", line 143, in explore
    page, app.config['POSTS_PER_PAGE'], False)
NameError: name 'app' is not defined
2020-01-02 12:29:28,695 ERROR: Exception on /index [GET] [in /Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/app/routes.py", line 29, in index
    page, app.config['POSTS_PER_PAGE', False])
NameError: name 'app' is not defined
2020-01-02 12:29:29,522 ERROR: Exception on /index [GET] [in /Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/app/routes.py", line 29, in index
    page, app.config['POSTS_PER_PAGE', False])
NameError: name 'app' is not defined
2020-01-02 12:29:30,230 ERROR: Exception on /index [GET] [in /Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/app/routes.py", line 29, in index
    page, app.config['POSTS_PER_PAGE', False])
NameError: name 'app' is not defined
2020-01-02 12:29:32,424 ERROR: Exception on /explore [GET] [in /Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/app/routes.py", line 143, in explore
    page, app.config['POSTS_PER_PAGE'], False)
NameError: name 'app' is not defined
2020-01-02 12:30:34,601 INFO: Microblog startup [in /Users/nathanphan/Desktop/Projects/flask/microblog/app/__init__.py:49]
2020-01-02 12:30:38,252 ERROR: Exception on /explore [GET] [in /Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanphan/Desktop/Projects/flask/microblog/app/routes.py", line 143, in explore
    page, application.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2020-01-02 12:31:11,602 INFO: Microblog startup [in /Users/nathanphan/Desktop/Projects/flask/microblog/app/__init__.py:49]
