2020-01-08 20:10:58,712 ERROR: Exception on /explore [GET] [in /Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/routes.py", line 151, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/templates/index.html", line 17, in root
    <span aria-hidden="true">&larr;</span>Newer Posts
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/templates/base.html", line 14, in root
    <div class="navbar-header">
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/templates/base.html", line 81, in block_content
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/templates/index.html", line 43, in block_app_content
  File "/Users/nathan/Desktop/Projects/flask/microblog/app/templates/_post.html", line 13, in root
    <br>
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/nathan/Desktop/Projects/flask/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user, username=post.author.username'. Did you mean 'reset_password_request' instead?
2020-01-08 20:11:36,903 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:53]
2020-01-08 20:20:48,588 INFO: Microblog startup [in /Users/nathan/Desktop/Projects/flask/microblog/app/__init__.py:55]
